# Generated by Django 5.2.6 on 2025-11-09 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0002_playerstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='total_losses',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='total_wins',
            new_name='wins',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='favorite_level',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/Goku.jpg', upload_to='memory_game/cards/'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='most_played_level',
            field=models.CharField(default='Básico', max_length=50),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('attempts_remaining', models.IntegerField(default=0)),
                ('pairs_found', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
